//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deep
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessTokens
    {
        public int id { get; set; }
        public string access_token { get; set; }
        public string refresh_token { get; set; }
        public System.DateTime last_refresh { get; set; }
    }
}
