//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deep
{
    using System;
    using System.Collections.Generic;
    
    public partial class Surveys
    {
        public int id { get; set; }
        public int id_project { get; set; }
        public string name_people { get; set; }
        public int age { get; set; }
        public string profession { get; set; }
        public string description { get; set; }
    }
}
