//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deep
{
    using System;
    using System.Collections.Generic;
    
    public partial class Variant
    {
        public Variant()
        {
            this.Answer = new HashSet<Answer>();
        }
    
        public int id { get; set; }
        public int question_id { get; set; }
        public string text { get; set; }
    
        public virtual ICollection<Answer> Answer { get; set; }
        public virtual Question Question { get; set; }
    }
}
